### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by ohmer1** [Lesmiscore/PhpApp#1]
Hello,

I was using your app, but unfortunately, the app is now unavailable on the Google Play Store. I tried to build the app. I succeeded to build the apk, but when opening the app on my device I get the following message:

```
Error - failed to obtain list od available versions with message:
NullPointerException, Attempt to invoke virtual method 'org.json.JSONArray org.json.JSONObject.getJSONArray(java.lang.String)' on a null object reference
```

I'm not sure, but I think I built the APK but not the required php binaries.

**Comment by Lesmiscore** [comment]
I'm sorry, but I forgot why I have this repo.     
Can you please ask about it to the original author @esminis ?     
I'll leave this open until problem resolves.

**Comment by esminis** [comment]
Due to hostile actions from Google this project is fully closed and not supported anymore (this means binaries are also not available anymore)

**Comment by ohmer1** [comment]
If you have some notes about compiling the binaries, could you provide it please? I would just compile it for my needs. 

Also I wonder if you have thought about publishing it to f-droid instead of the Play store.

Thank you!

**Comment by esminis** [comment]
For compiling - simply do cross-compiling, but it usually takes lots of work (especially for Mongo / Apache).
Publishing to f-droid will not help much as issue is with Android itself.

**Comment by Lesmiscore** [comment]
Closing this as the original author says it is unsupported anymore.
